import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';

import ThemeProvider from '@/theme/ThemeProvider';
import Navbar from '@/components/navbar/Navbar';
import Footer from '@/components/footer/Footer';
import '@/styles/globals.css';

const font = Raleway({
  subsets: ['latin'],
  weight: ['300', '400', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-white dark:bg-background`}>
        <ThemeProvider>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
